name: SevenDungeons
main: seven.dungeons.SevenDungeons
version: 1.0.0
api-version: 1.19
depend: [Multiverse-Core, Citizens]
description: Dungeon framework plugin.
commands:
    7d:
        description: "Dungeons commands"
        permission:
        usage: /7d
    party:
        description: "Party commands"
        permission:
        usage: /party
    leave:
        description: "Leave command"
        permission:
        usage: /leave